import { writeFileSync, mkdirSync } from "fs";
import { join } from "path";
import type { CurationResult } from "./types";

function todayStr(): string {
  return new Date().toISOString().split("T")[0];
}

export function renderReport(result: CurationResult, outputDir: string): string {
  const date = todayStr();
  const lines: string[] = [];

  lines.push(`# Daily Report — ${date}`);
  lines.push("");
  lines.push(
    "> React with `+1` or `-1` at the end of any article line to improve future recommendations."
  );
  lines.push("");

  for (const category of result.categories) {
    lines.push(`## ${category.name}`);
    lines.push("");
    category.articles.forEach((article, i) => {
      lines.push(
        `${i + 1}. [${article.title}](${article.url}) — *${article.source}* — ${article.reason}`
      );
    });
    lines.push("");
  }

  lines.push("## Wildcard Pick");
  lines.push("");
  lines.push(
    `> [${result.wildcard.title}](${result.wildcard.url}) — *${result.wildcard.source}*`
  );
  lines.push(`> ${result.wildcard.reason}`);
  lines.push("");
  lines.push("---");
  lines.push(
    "*Generated by [dailyreport](https://github.com/your-username/dailyreport) using Claude claude-sonnet-4-6*"
  );

  const content = lines.join("\n");
  const projectRoot = join(import.meta.dir, "..");
  const dir = join(projectRoot, outputDir);
  mkdirSync(dir, { recursive: true });
  const filePath = join(dir, `${date}.md`);
  writeFileSync(filePath, content, "utf-8");
  return filePath;
}
